[package]
name = "sub_service"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
log = "0.4"
env_logger = "0.11.3"
[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
